/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HomePageLabel = new javax.swing.JLabel();
        DoctorsInfoButton = new javax.swing.JButton();
        NurseInfoButton = new javax.swing.JButton();
        PatientInfoButton = new javax.swing.JButton();
        AppointmentButton = new javax.swing.JButton();
        HospitalInfoButton = new javax.swing.JButton();
        AddNewPatientButton = new javax.swing.JButton();
        RecoverPatientButton = new javax.swing.JButton();
        PayBillButton = new javax.swing.JButton();
        HelthTestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        HomePageLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomePageLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomePageLabel.setText("Home Page");

        DoctorsInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DoctorsInfoButton.setText("Doctor's info");
        DoctorsInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsInfoButtonActionPerformed(evt);
            }
        });

        NurseInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NurseInfoButton.setText("Nurse Info");
        NurseInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseInfoButtonActionPerformed(evt);
            }
        });

        PatientInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PatientInfoButton.setText("patient Info");
        PatientInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientInfoButtonActionPerformed(evt);
            }
        });

        AppointmentButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AppointmentButton.setText("Appointment  ");
        AppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentButtonActionPerformed(evt);
            }
        });

        HospitalInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HospitalInfoButton.setText("Hospital Info");
        HospitalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalInfoButtonActionPerformed(evt);
            }
        });

        AddNewPatientButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddNewPatientButton.setText("Add new patient  ");
        AddNewPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewPatientButtonActionPerformed(evt);
            }
        });

        RecoverPatientButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RecoverPatientButton.setText("Recover Patient ");
        RecoverPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoverPatientButtonActionPerformed(evt);
            }
        });

        PayBillButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PayBillButton.setText("Pay Bill  ");
        PayBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBillButtonActionPerformed(evt);
            }
        });

        HelthTestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HelthTestButton.setText("Health Test  ");
        HelthTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelthTestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomePageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddNewPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoctorsInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HelthTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospitalInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PayBillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(NurseInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PatientInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AppointmentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RecoverPatientButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorsInfoButton)
                    .addComponent(NurseInfoButton)
                    .addComponent(PatientInfoButton))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppointmentButton)
                    .addComponent(HospitalInfoButton)
                    .addComponent(AddNewPatientButton))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RecoverPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HelthTestButton)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NurseInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseInfoButtonActionPerformed
        // TODO add your handling code here:
        NurseInfoFrame frame=new NurseInfoFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_NurseInfoButtonActionPerformed

    private void DoctorsInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsInfoButtonActionPerformed
        // TODO add your handling code here:
        DoctorInfoFrame frame=new DoctorInfoFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_DoctorsInfoButtonActionPerformed

    private void PatientInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientInfoButtonActionPerformed
        // TODO add your handling code here:
        PatientInfoJFrame frame=new PatientInfoJFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_PatientInfoButtonActionPerformed

    private void AddNewPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewPatientButtonActionPerformed
        // TODO add your handling code here:
        AddNewPatientFram frame=new AddNewPatientFram();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddNewPatientButtonActionPerformed

    private void HospitalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalInfoButtonActionPerformed
        // TODO add your handling code here:
        HospitalInfoFrame frame=new HospitalInfoFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_HospitalInfoButtonActionPerformed

    private void AppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentButtonActionPerformed
        // TODO add your handling code here:
        AppointmentFrame frame=new AppointmentFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_AppointmentButtonActionPerformed

    private void HelthTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelthTestButtonActionPerformed
        // TODO add your handling code here:
        HealthTestFrame frame=new HealthTestFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_HelthTestButtonActionPerformed

    private void PayBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBillButtonActionPerformed
        // TODO add your handling code here:
         PayBill frame=new PayBill();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_PayBillButtonActionPerformed

    private void RecoverPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoverPatientButtonActionPerformed
        // TODO add your handling code here:
         RecoverPatientFrame frame=new RecoverPatientFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_RecoverPatientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewPatientButton;
    private javax.swing.JButton AppointmentButton;
    private javax.swing.JButton DoctorsInfoButton;
    private javax.swing.JButton HelthTestButton;
    private javax.swing.JLabel HomePageLabel;
    private javax.swing.JButton HospitalInfoButton;
    private javax.swing.JButton NurseInfoButton;
    private javax.swing.JButton PatientInfoButton;
    private javax.swing.JButton PayBillButton;
    private javax.swing.JButton RecoverPatientButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
