
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class PayBill extends javax.swing.JFrame {

    /**
     * Creates new form PayBill
     */
    public PayBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PaybillLabel = new javax.swing.JLabel();
        SelectPaymentMethodLabel = new javax.swing.JLabel();
        EnterAccountNumberLabel = new javax.swing.JLabel();
        EnterNumberLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        SelectPaymentMethodComboBox = new javax.swing.JComboBox<>();
        BillSentButton = new javax.swing.JButton();
        PayBillBackButtonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        PaybillLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PaybillLabel.setForeground(new java.awt.Color(255, 255, 255));
        PaybillLabel.setText("Pay Bill");

        SelectPaymentMethodLabel.setForeground(new java.awt.Color(255, 255, 255));
        SelectPaymentMethodLabel.setText("Select Payment Method");

        EnterAccountNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterAccountNumberLabel.setText("Enter Your Account Number");

        EnterNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterNumberLabel.setText("Enter Amount");

        SelectPaymentMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bkash", "Nagad" }));

        BillSentButton.setText("Sent");
        BillSentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillSentButtonActionPerformed(evt);
            }
        });

        PayBillBackButtonButton.setText("Back");
        PayBillBackButtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBillBackButtonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(PaybillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(EnterAccountNumberLabel)
                                            .addComponent(SelectPaymentMethodLabel)
                                            .addComponent(EnterNumberLabel))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SelectPaymentMethodComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(BillSentButton)))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PayBillBackButtonButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaybillLabel)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectPaymentMethodLabel)
                    .addComponent(SelectPaymentMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterAccountNumberLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterNumberLabel)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BillSentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(PayBillBackButtonButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BillSentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillSentButtonActionPerformed
        // TODO add your handling code here:
          String method="",accountnumber="",amount="";
       
          
          
          
          try {
            method=SelectPaymentMethodComboBox.getItemAt(SelectPaymentMethodComboBox.getSelectedIndex());
            
             if(method.isEmpty()){
               
                JOptionPane.showMessageDialog(this, "Select Your Method");
            }
        } catch (Exception e) {
        }
        
        
        try {
            accountnumber=jTextField1.getText();
            
            if(accountnumber.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Your Account Number");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something woring with your account number");
        }
        
         try {
            amount=jTextField2.getText();
            
            if(amount.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Your Address");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something woring with your address");
        }
        
        
        
        if(!(accountnumber.isEmpty() || amount.isEmpty() )){
            PaybillClass paybillClass=new PaybillClass();
            paybillClass.setValue(method, accountnumber, amount);
            paybillClass.dataWriteinFile();
            JOptionPane.showMessageDialog(this, "Congress");
        }
    }//GEN-LAST:event_BillSentButtonActionPerformed

    private void PayBillBackButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBillBackButtonButtonActionPerformed
        // TODO add your handling code here:
        HomeFrame homeFrame=new HomeFrame();
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_PayBillBackButtonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillSentButton;
    private javax.swing.JLabel EnterAccountNumberLabel;
    private javax.swing.JLabel EnterNumberLabel;
    private javax.swing.JButton PayBillBackButtonButton;
    private javax.swing.JLabel PaybillLabel;
    private javax.swing.JComboBox<String> SelectPaymentMethodComboBox;
    private javax.swing.JLabel SelectPaymentMethodLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
