
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class RecoverPatientFrame extends javax.swing.JFrame {

    /**
     * Creates new form RecoverPatientFrame
     */
    public RecoverPatientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RecoverpatientLabel = new javax.swing.JLabel();
        RecoverpatientNameLabel = new javax.swing.JLabel();
        RecoverPatientDiseaseLabel = new javax.swing.JLabel();
        RecoverPatientReleaseButton = new javax.swing.JButton();
        RecoverPatientBackButton = new javax.swing.JButton();
        RecoverPatientNameTextField = new javax.swing.JTextField();
        RecoverPatientDiseaseNameComboBox = new javax.swing.JComboBox<>();
        RecoverpatientNameLabel1 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        RecoverpatientLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RecoverpatientLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecoverpatientLabel.setText("Recover Patient   ");

        RecoverpatientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecoverpatientNameLabel.setText(" Patient Name");

        RecoverPatientDiseaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecoverPatientDiseaseLabel.setText("Disease Name");

        RecoverPatientReleaseButton.setText("Release");
        RecoverPatientReleaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoverPatientReleaseButtonActionPerformed(evt);
            }
        });

        RecoverPatientBackButton.setText("Back");
        RecoverPatientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoverPatientBackButtonActionPerformed(evt);
            }
        });

        RecoverPatientDiseaseNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diabetics", "Covid19", "Cold Fever" }));

        RecoverpatientNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        RecoverpatientNameLabel1.setText(" Patient Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(RecoverpatientLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RecoverpatientNameLabel)
                                            .addComponent(RecoverPatientDiseaseLabel))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RecoverPatientDiseaseNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RecoverPatientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RecoverpatientNameLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(RecoverPatientReleaseButton)))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RecoverPatientBackButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RecoverpatientLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecoverpatientNameLabel)
                    .addComponent(RecoverPatientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecoverpatientNameLabel1)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecoverPatientDiseaseLabel)
                    .addComponent(RecoverPatientDiseaseNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(RecoverPatientReleaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(RecoverPatientBackButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecoverPatientBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoverPatientBackButtonActionPerformed
        // TODO add your handling code here:
        HomeFrame homeFrame=new HomeFrame();
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_RecoverPatientBackButtonActionPerformed

    private void RecoverPatientReleaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoverPatientReleaseButtonActionPerformed
        // TODO add your handling code here:
        String name="",disease="",address="";
        
        try {
            name=RecoverPatientNameTextField.getText();
            
            if(name.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Your Name");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something woring with your name");
        }
        
         try {
            address=addressTF.getText();
            
            if(address.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Your Address");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something woring with your address");
        }
        
        
        try {
            disease=RecoverPatientDiseaseNameComboBox.getItemAt(RecoverPatientDiseaseNameComboBox.getSelectedIndex());
            
             if(disease.isEmpty()){
                JOptionPane.showMessageDialog(this, "Select Your Disease");
            }
        } catch (Exception e) {
        }
        
        if(!(name.isEmpty() || address.isEmpty() || disease.isEmpty())){
            JOptionPane.showMessageDialog(this, "Congress Patient Recever Successfully");
        }
        
    }//GEN-LAST:event_RecoverPatientReleaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RecoverPatientBackButton;
    private javax.swing.JLabel RecoverPatientDiseaseLabel;
    private javax.swing.JComboBox<String> RecoverPatientDiseaseNameComboBox;
    private javax.swing.JTextField RecoverPatientNameTextField;
    private javax.swing.JButton RecoverPatientReleaseButton;
    private javax.swing.JLabel RecoverpatientLabel;
    private javax.swing.JLabel RecoverpatientNameLabel;
    private javax.swing.JLabel RecoverpatientNameLabel1;
    private javax.swing.JTextField addressTF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
